version: '3'
services:
    notebook:
        build: './docker-notebook'
        ports:
            - '8888:8888'
        volumes:
            - './data:/home/jovyan'
        command: "start-notebook.sh --NotebookApp.token=''"


